Websphere/ihs 90518
merative/spm-middleware pull request #69
Opened 2024-02-06 13:00 UTC by romakarol

## Summary

Add version files for ihs and websphere v...18

## Story

https://github.com/spm-devops/transformers/issues/932

## Test

Tested locally with `ansible-playbook -i ./hosts --become --private-key=/Users/romakarol/.ssh/id_main_slave_rsa  ./play.yml -e ' websphere_version=9.0.5.18  ihs_version=9.0.5.18 ant_version=1.10.6 ' -e artifactory_token=***`

<img width="960" alt="image" src="https://github.com/merative/spm-middleware/assets/32648346/8282c736-c989-46de-856a-84f7c797e977">

<img width="561" alt="image" src="https://github.com/merative/spm-middleware/assets/32648346/afb0de64-bd30-4cd4-a8d4-4813eb721cb8">

2024-02-06 13:33 UTC, ourboy requested changes
- in the galaxy.yml you need to update the version
- update the converge for both IHS and WAS to be the latest version 
- update molecule/iim-191-rockylinux8/converge.yml
- was IIM not updated?
- update roles/ihs/README.md

2024-02-06 14:04 UTC, romakarol commented
Nothing in the story about IIM, Ill see what was uploaded/needs to be updated.
The rest is done except the IIM converge, I need to match that to whatever Ill  add now.

Dont see the value in updating IHS READMEof time it is half-updated half-not. I did it for now maybe we can consider just pointing it to the latest var file instead of copying the same info over.

2024-02-06 14:15 UTC, romakarol commented
Its actually silly how many places I needed to change with that second commit, we should centralise these to only change in 1 place. One for the retro!

2024-02-08 09:52 UTC, ourboy approved these changes

2024-02-08 12:21 UTC, merged